import nodemailer from 'nodemailer';
import { env } from '$env/dynamic/private';
import type { PrayerRequest } from './prayerRequests';

interface EmailConfig {
	host: string;
	port: number;
	secure: boolean;
	auth: {
		user: string;
		pass: string;
	};
}

interface EmailOptions {
	to: string | string[];
	subject: string;
	html: string;
}

export class EmailService {
	private transporter: nodemailer.Transporter;

	constructor() {
		const config: EmailConfig = {
			host: env.SMTP_HOST || 'smtp.gmail.com',
			port: parseInt(env.SMTP_PORT || '587'),
			secure: env.SMTP_SECURE === 'true',
			auth: {
				user: env.SMTP_USER || '',
				pass: env.SMTP_PASS || ''
			}
		};

		this.transporter = nodemailer.createTransport(config);
	}

	async sendPrayerRequestsEmail(
		requests: PrayerRequest[],
		recipients: string[],
		options: {
			startDate?: Date;
			endDate?: Date;
			includeStaffOnly?: boolean;
		} = {}
	): Promise<boolean> {
		try {
			const { startDate, endDate, includeStaffOnly } = options;

			// Filter requests based on options
			let filteredRequests = requests;
			if (startDate) {
				filteredRequests = filteredRequests.filter((r) => new Date(r.submittedAt) >= startDate);
			}
			if (endDate) {
				filteredRequests = filteredRequests.filter((r) => new Date(r.submittedAt) <= endDate);
			}
			if (!includeStaffOnly) {
				filteredRequests = filteredRequests.filter((r) => !r.isStaffOnly);
			}

			if (filteredRequests.length === 0) {
				console.log('No prayer requests to send');
				return false;
			}

			const html = this.generatePrayerRequestsHTML(filteredRequests, options);

			const emailOptions: EmailOptions = {
				to: recipients,
				subject: 'Westwoods Prayer Requests',
				html
			};

			await this.transporter.sendMail(emailOptions);
			console.log(`Prayer requests email sent to ${recipients.length} recipients`);
			return true;
		} catch (error) {
			console.error('Error sending prayer requests email:', error);
			return false;
		}
	}

	private generatePrayerRequestsHTML(
		requests: PrayerRequest[],
		options: {
			startDate?: Date;
			endDate?: Date;
			includeStaffOnly?: boolean;
		}
	): string {
		const { startDate, endDate, includeStaffOnly } = options;

		let dateRangeText = '';
		if (startDate && endDate) {
			dateRangeText = ` from ${startDate.toLocaleDateString()} to ${endDate.toLocaleDateString()}`;
		} else if (startDate) {
			dateRangeText = ` from ${startDate.toLocaleDateString()}`;
		} else if (endDate) {
			dateRangeText = ` until ${endDate.toLocaleDateString()}`;
		}

		const staffOnlyText = includeStaffOnly ? ' (including staff-only requests)' : '';

		let html = `
			<!DOCTYPE html>
			<html>
			<head>
				<meta charset="utf-8">
				<title>Westwoods Prayer Requests</title>
				<style>
					body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
					.container { max-width: 600px; margin: 0 auto; padding: 20px; }
					.header { background: #4a90e2; color: white; padding: 20px; text-align: center; }
					.request { background: #f9f9f9; margin: 20px 0; padding: 20px; border-left: 4px solid #4a90e2; }
					.requestText { margin-bottom: 10px; }
					.requestMeta { font-size: 0.9em; color: #666; }
					.staffBadge { background: #ffd700; color: #333; padding: 2px 8px; border-radius: 3px; font-size: 0.8em; font-weight: bold; }
					.footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 0.9em; color: #666; }
				</style>
			</head>
			<body>
				<div class="container">
					<div class="header">
						<h1>Westwoods Prayer Requests</h1>
						<p>Prayer requests${dateRangeText}${staffOnlyText}</p>
					</div>
		`;

		requests.forEach((request) => {
			const date = new Date(request.submittedAt).toLocaleDateString('en-US', {
				year: 'numeric',
				month: 'short',
				day: 'numeric',
				hour: '2-digit',
				minute: '2-digit'
			});

			html += `
				<div class="request">
					<div class="requestText">${request.request.replace(/\n/g, '<br>')}</div>
					<div class="requestMeta">
						Submitted: ${date}
						${request.name ? `<br>From: ${request.name}` : ''}
						${request.isStaffOnly ? '<br><span class="staffBadge">Staff Only</span>' : ''}
					</div>
				</div>
			`;
		});

		html += `
					<div class="footer">
						<p>This email was automatically generated by the Westwoods Prayer Request system.</p>
						<p>Total requests: ${requests.length}</p>
					</div>
				</div>
			</body>
			</html>
		`;

		return html;
	}

	async testConnection(): Promise<boolean> {
		try {
			await this.transporter.verify();
			console.log('Email service connection verified');
			return true;
		} catch (error) {
			console.error('Email service connection failed:', error);
			return false;
		}
	}
}

export const emailService = new EmailService();
